name: iOS LLVM
on:
   workflow_dispatch:
jobs:
   build:
      runs-on: macos-latest
      steps:
         - uses: actions/checkout@v6
         - run: |
            chmod +x build.sh
            ./build.sh
