name: iOS LLVM

on:
  workflow_dispatch:

jobs:
  build:
    name: Build (${{ matrix.target }}, ${{ matrix.mode_type }}, ${{ matrix.build_type }})
    strategy:
      matrix:
        build_type: [ Release, Debug ]
        mode_type: [ Native, Cross-Host, Cross-CMake ]
        target: [ ios-arm64, ios-simulator-arm64, ios-simulator-x86_64 ]
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Build
        run: |
          chmod +x build.sh
          ./build.sh "${{ matrix.target }}" "${{ matrix.mode_type }}" "${{ matrix.build_type }}"
